stages:
- build-container
- build-software

variables:
  IMAGE_NAME: psquarejho/factorio-server-manager
  GIT_SSL_NO_VERIFY: "1"
  FACTORIO_VERSION: $CI_COMMIT_TAG

before_script:
  - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-container:
  stage: build-container
  tags:
    - shell
  only:
    - tags
    - triggers
    - pipelines
    - web
  script:
    - docker build -t $IMAGE_NAME:$FACTORIO_VERSION -t $IMAGE_NAME:latest --build-arg FACTORIO_VERSION=$FACTORIO_VERSION docker/
    - docker push $IMAGE_NAME:$FACTORIO_VERSION
    - docker push $IMAGE_NAME:latest

build-software:
  stage: build-software
  tags:
  - docker
  image: golan:1.12-alpine
  script:
   - make