stages:
- build

variables:
  IMAGE_NAME: psquarejho/factorio-server-manager
  GIT_SSL_NO_VERIFY: "1"

before_script:
  - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  tags:
    - shell
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG -t $IMAGE_NAME:latest --build-arg FACTORIO_VERSION=$CI_COMMIT_TAG docker/
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME:latest
