stages:
- build-container
- build-software

variables:
  IMAGE_NAME: psquarejho/factorio-server-manager
  GIT_SSL_NO_VERIFY: "1"
  FACTORIO_VERSION: $CI_COMMIT_TAG


build-container:
  stage: build-container
  tags:
    - shell
  
  only:
    - tags
    - triggers
    - pipelines
    - web
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$FACTORIO_VERSION -t $IMAGE_NAME:latest --build-arg FACTORIO_VERSION=$FACTORIO_VERSION docker/
    - docker push $IMAGE_NAME:$FACTORIO_VERSION
    - docker push $IMAGE_NAME:latest

build-frontend:
  stage: build-software
  tags:
   - docker
  image: node:carbon-alpine
  script:
   - npm install
   - npm run build
   - ls app/
  artifacts:
    paths:
     - app/bundle.js
     - app/style.css
     - app/index.html
     - app/fonts/vendor
     - app/images/vendor

build-backend:
  stage: build-software
  tags:
    - docker
  image: golang:1.7
  script:
    - go build -o factorio-server-manager ./src
  artifacts:
    paths:
      - factorio-server-manager